import 'dotenv/config';
import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import morgan from 'morgan';
import path from 'path';
import { fileURLToPath } from 'url';
import authRoutes from './routes/authRoutes.js';
import courseRoutes from './routes/courseRoutes.js';
import dashboardRoutes from './routes/dashboardRoutes.js';
import facultyRoutes from './routes/facultyRoutes.js';
import mentoringRoutes from './routes/mentoringRoutes.js';
import { errorHandler } from './middleware/errorHandler.js';

const app = express();
const root = path.dirname(fileURLToPath(import.meta.url));
app.use(helmet({ crossOriginResourcePolicy: false }));
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173' }));
app.use(express.json({ limit: '1mb' }));
app.use(morgan('dev'));
app.use('/uploads', express.static(path.join(root, '../uploads')));
app.get('/api/health', (req, res) => res.json({ status: 'ok', service: 'AIML AcademicHub API' }));
app.use('/api/auth', authRoutes);
app.use('/api/faculty', facultyRoutes);
app.use('/api/courses', courseRoutes);
app.use('/api/mentoring', mentoringRoutes);
app.use('/api/faculty/dashboard', dashboardRoutes);
app.use(errorHandler);
export default app;